title: stefins
email: stefin2016@gmail.com
description: This is my personal blog
baseurl: "/"
url: "https://stefins.github.io" 
twitter_username: stef1ns
github_username:  stefins

theme: minima
